#!/usr/bin/env bash

work_dir=$(pwd)

data_dir="$work_dir/data"
jixia_dir="$work_dir/jixia"
jixia="$work_dir/jixia/.lake/build/bin/jixia"
mathlib_dir="$work_dir/mathlib4"
module="Mathlib"

# build mathlib first
cd $mathlib_dir && lake build

# jixia must use the same lean version with mathlib
cp $mathlib_dir/lean-toolchain $jixia_dir/
cd $jixia_dir && lake build

# generate graph
cd $mathlib_dir && lake env $jixia \
	-d $data_dir/$module.decl.json \
	-s $data_dir/$module.sym.json \
	-e $data_dir/$module.elab.json \
	-l $data_dir/$module.lines.json \
	$module.lean


cd $work_dir
