#!/usr/bin/env bash

work_dir=$(pwd)

jixia_dir="$work_dir/jixia"
jixia="$work_dir/jixia/.lake/build/bin/jixia"
mathlib_dir="$work_dir/mathlib4"
module="Mathlib"

# build mathlib first
cd $mathlib_dir && lake build

# jixia must use the same lean version with mathlib
cp $mathlib_dir/lean-toolchain $jixia_dir/
cd $jixia_dir && lake build

# generate graph
cd $mathlib_dir && lake env $jixia \
	-d $module.decl.json \
	-s $module.sym.json \
	-e $module.elab.json \
	-l $module.lines.json \
	$module.lean


cd $work_dir
