#!/usr/bin/env bash

work_dir=$(pwd)



jixia_dir="$work_dir/jixia"
jixia="$work_dir/jixia/.lake/build/bin/jixia"
mathlib_dir="$work_dir/mathlib4"
module="Mathlib"


cd $jixia_dir && lake build
cd $mathlib_dir && lake build

cd $mathlib_dir && lake env $jixia \
	-d $module.decl.json \
	-s $module.sym.json \
	-e $module.elab.json \
	-l $module.lines.json \
	$module.lean

